### ISSUE TITLE
Enhancement: Support zig fmt 

### ISSUE THREAD

**Issue by el10savio** [gsquire/zig-play#10]
Similar to Go Playground, I was wondering if we could possibly add an `fmt` option too in the zig-play. To format the user's source zig code in the textarea. 

Wanted to run it by you if it was feasible to handle sending the source code as a payload, formatting it, and then updating the source text area with the formatted code or displaying fmt warnings (if any) in the `stdout` box.

Something along these lines:

```
$ echo 'const std = @import("std"); pub fn main() void { std.debug.print("Hello, {s}!", .{"world"}); }' | zig fmt --stdin
const std = @import("std");
pub fn main() void {
    std.debug.print("Hello, {s}!", .{"world"});
}
```

**Comment by gsquire** [comment]
I think that's a good idea to add. Unfortunately I don't know if there is a way to capture the output of `zig fmt` but I imagine we can just read the temporary file again after the fact.

I'd be happy to review anything if you feel up for it.

**Comment by el10savio** [comment]
Sure, I can try it out if it's feasible and raise a PR.
