### ISSUE TITLE
SSL handshake failed on zig-play.dev

### ISSUE THREAD

**Issue by speps** [gsquire/zig-play#15]
I'm hitting this error when going to https://zig-play.dev (on 2 different ISPs I could try at home):

<img width="880" alt="Screenshot 2023-02-05 at 18 40 00" src="https://user-images.githubusercontent.com/16678/216838526-eb070a6d-9b16-46fd-a59d-d49691710196.png">

**Comment by gsquire** [comment]
Hello, sorry for the errors. I recently switched hosting providers and I think I missed the expiry date here. It should be good to go now.

**Comment by speps** [comment]
All good, thanks a lot!
