### ISSUE TITLE
Compiler version is outdated

### ISSUE THREAD

**Issue by jarble** [gsquire/zig-play#7]
I tried running this program in the Zig playground, but it doesn't compile successfully. This might be due to an outdated version of the Zig compiler:

```
const std = @import("std");

// we make the interface very explicit here.
// Might also be possible with less comptime parameters, but could be way more ugly then
fn map(comptime Src: type, comptime Dst: type, comptime len: usize, array: [len]Src, function: fn(Src) Dst) [len]Dst {
    var result: [len]Dst = undefined;
    for (result) |*res ,index| {
        res.* = function(array[index]);
    }
    return result;
}

fn add(a: f64) f64 {
    return a + 1.0;
}

pub fn main() void {
    var array_thing = map(
        f64, // src type
        f64, // dst type
        3,   // array length
        .{1.0, 2.0,3.0},  // anonymous literal, can be coerced to array
        add, // the function
    );
    std.debug.print("Hello, {d}!", .{array_thing}); // prints "Hello, { 2, 3, 4 }!"
}
```
Will the Zig playground be automatically updated to use the latest compiler version, or does it still need to be updated manually?

**Comment by gsquire** [comment]
The docker container will need to be rebuilt. I can do this soon and get it to the latest stable version. I will look into automating it but I don't know how simple that will be.

**Comment by gsquire** [comment]
I tested your snippet after updating it but let me know if it still fails for you.

**Comment by gsquire** [comment]
This seems to have gone stale. Please open a new issue if you still have a problem.
